name: Pull request test
on: [pull_request, workflow_dispatch]
jobs:
  cypress-run:
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'RFR')
    name: Cypress run
    runs-on: self-hosted
    steps:
        # Checkout to pull request branch
      - name: Checkout
        uses: actions/checkout@v2
        # Install NPM dependencies
      - name: Install NPM
        run: npm install .
        # Get all the files added to pull request
      - id: file_changes
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
        # Create event to generate ouput of comma separated test files only
      - id: event
        run: |
          test_files=`python3 -c 'print(",".join([file for file in ${{ steps.file_changes.outputs.all }} if ".test.ts" in file]))'`
          echo "::set-output name=tests::$test_files"
          echo "::set-output name=tackleUrl::'https://tackle-qe-app-inventory.apps.mta01.cnv-qe.rhcloud.com'"
      - name: Run cypress test cases
        if: ${{ steps.event.outputs.tests }}
        run: npx cypress run --spec ${{ steps.event.outputs.tests }} --env user="tackle",pass="password",tackleUrl=${{ steps.event.outputs.tackleUrl }} --config video=false
